In [13]:
# 파이토치 설치
# !pip install torch torchvision torchaudio

- torch : pytorch의 핵심 패키지
- torchivision : 컴퓨터 비전을 위한 데이터셋, 모델 아키텍처, 이미지 변환 등
- torchaudio : 오디오 처리와 관련된 도구의 라이브러리

#### Tensor
- 머신러닝과 딥러닝에서 사용되는 기본적인 구조
- 다차원 배열과 숫자데이터를 저장하고 조작하는데 사용

##### Tensor의 특징
- 다차원 배열 : Tensor는 1차원(벡터), 2차원(행렬), 3차원 이상의 다차원 데이터를 표현
- GPU 지원 : Tensor는 GPU에서 연산을 수행할 수 있어 빠른 계산이 가능
- 자동 미분 :  Tensor는 자동 미분(AutoGrad) 기능을 지원하여 딥러닝 모델의 학습에 필요한 기울기 계산을 자동으로 수행 한다.

In [14]:
# Tensor의 생성
import torch

# 1차원 Tensor 생성
t1 = torch.tensor([1,2,3,4])
print(t1) # 넘파이보다 작은 단위로 쓸 수 있는게 tensor 임

tensor([1, 2, 3, 4])


In [15]:
# 2차원 Tensor
t2 = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
print(t2)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [16]:
# 
print(t1.shape)
print(t2.shape)

torch.Size([4])
torch.Size([3, 3])


In [17]:
# Tensor의 타입 확인 및 변경
print(t1.dtype)
t1_float = t1.float()
print(t1_float.dtype)
print(t1_float)

torch.int64
torch.float32
tensor([1., 2., 3., 4.])


In [18]:
# Tensor의 연산
a =torch.tensor([1,2,3])
b =torch.tensor([4,5,6])

print(a+b)
print(a*b)

tensor([5, 7, 9])
tensor([ 4, 10, 18])


In [19]:
# Tensor의 Indexing과 Slicing

t= torch.tensor(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
    ]
)

print(t)
print(t[1,1])
print(t[1,-1])
print(t[1:-1])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(5)
tensor(6)
tensor([[4, 5, 6]])


In [20]:
# Boolen Indexing
t1 = torch.tensor([1,2,3,4,5])
t1[t1 > 3]

tensor([4, 5])

In [21]:
# reshape
t = torch.tensor([1,2,3,4,5,6])
t_reshaped = t.reshape(2, 3)
t_reshaped

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
# view
t_viewed = t.view(2,3)
t_viewed

tensor([[1, 2, 3],
        [4, 5, 6]])

In [23]:
# Tensor의 차원변경 : squeeze, unsqueeze

t = torch.tensor([1,2,3])
print(t)
print(t.shape)
print("-" * 15)

t_unsqueezed = t.unsqueeze(0) # 지정한 위치에 크기가 1인 차원을 추가 
print(t_unsqueezed)
print(t_unsqueezed.shape)
print("-" * 15)

t_unsqueezed_squeeze = t_unsqueezed.squeeze(0) # 지정한 위치에 크기가 1인 차원을 제거(그 차원의 크기가 1일때만 제거)
print(t_unsqueezed)
print(t_unsqueezed.shape)
print("-" * 15)


tensor([1, 2, 3])
torch.Size([3])
---------------
tensor([[1, 2, 3]])
torch.Size([1, 3])
---------------
tensor([[1, 2, 3]])
torch.Size([1, 3])
---------------


In [24]:
# Ex : 
x = torch.ones(2, 1, 2)
print(x)
print(x.shape)
print("-" * 15)

# 모든 크기가 1인 차원 제거

x_squeezed = x.squeeze()  # 한개밖에 없어서 그냥 아무것도 안써도 된다 
x_squeezed = x.squeeze(dim=1)  # 몇번째꺼 지울건지 정해줄 수도 있음
print(x_squeezed)
print(x_squeezed.shape)
print("-" * 15)


tensor([[[1., 1.]],

        [[1., 1.]]])
torch.Size([2, 1, 2])
---------------
tensor([[1., 1.],
        [1., 1.]])
torch.Size([2, 2])
---------------


In [25]:
# torch의 연결
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([4,5,6])
torch.cat([t1, t2])

tensor([1, 2, 3, 4, 5, 6])

In [26]:
# Tensor의 수학함수 사용
t = torch.tensor([1.0 ,2.0, 3.0]) # 수학함수 쓰려면 무조건 실수로 적어야 함 _ 기본이 그렇다
print(torch.sin(t))
print(torch.mean(t))
print(torch.sum(t))
print(torch.sum(t))

tensor([0.8415, 0.9093, 0.1411])
tensor(2.)
tensor(6.)
tensor(6.)


In [27]:
# 행렬 곱셈 
t1 = torch.tensor(
    [
        [1,2,3], # 이건 열이 세개
        [4,5,6]
    ]
)

t2 = torch.tensor(
    [
        [7], # 이건 행이 3개
        [8],
        [9]
    ]
)

torch.matmul(t1, t2)
print(1*7 + 2*8 + 3*9)
print(4*7 + 5*8 + 6*9)
# 두개 모양이 다르니, 일반곱이 아니라 행렬곱으로 해줘야 한다 

50
122


In [28]:
C = torch.matmul(t1, t2)
print(C)

tensor([[ 50],
        [122]])


---
#### DataSet
- 데이터의 전처리와 모델학습을 효율적으로 수행하기 위한 핵심 구성 요소
- DataSet 데이터와 라벨을 저장
- DataLoader는 이러한 데이터를 쉽게 순회 할 수 있게 한다. (순회 : 섞어두고서 쓰는 거-> 과대적합이 덜 일어나게 하기 위해서)

#### DataSet과 DataLoader의 개념

##### DataSet
- 역할 : 데이터 샘플과 그에 해당하는 레이블을 저장
- 주요 Method
    - init : 데이터셋 초기화 및 데이터 로드 
    - len : 데이터셋의 샘플 갯수를 반환
    - getitem : 주어진 인덱스에 해당하는 샘플을 반환

##### DataLoader
- 역할 : DataSet을 Batch 단위로 쉽게 접근할 수 있도록 하는 iterable  :-> iterable 객체를 제공 (리스트)데이터 하나에 여러개 들어있는 데이터
- 주요 Method
    batch_size : 한번에 불러올 데이터의 크기
    - shuffle : 데이터를 무작위로 섞을지 여부
    - num_workers : 데이터를 로드할때 사용한 서브 프로세스의 수 

In [29]:
# 클래스 만들기
# 기본 데이터셋 클래스 정의
from torch.utils.data import Dataset # Dataset이라는 기본 클래스를 상속 받음

class SimpleDataset(Dataset):
    def __init__(self, data, labels): # 시스템에서 쓰는 건 다 언더바 두개씀/ 그래서 우리가 만드는거에 언더바 쓰면 안된다 -> 한개까지는 가능
        self.data = data
        self.labels = labels

    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):
        return self.data[idx], self.labels[idx], 

In [30]:
data = [[1,2], [3,4], [5,6]]
labels = [0,1,0]
dataset = SimpleDataset(data, labels) 

In [31]:
print(dataset.data)
print(dataset.labels)
print(len(dataset))
print(dataset[1])

[[1, 2], [3, 4], [5, 6]]
[0, 1, 0]
3
([3, 4], 1)


In [32]:
# 데이터셋은 리스트도 아니고 객체이다

In [33]:
# 기본 Dataloader 사용 : Shuffle 하지 않고 전체를 한번에 사용하자 batch_size=3

from torch.utils.data import DataLoader

dataloder = DataLoader(dataset, batch_size=3, shuffle=False)

for batch in dataloder:
    print(batch)

[[tensor([1, 3, 5]), tensor([2, 4, 6])], tensor([0, 1, 0])]


In [34]:
# shuffle하고 2개씩 불러오기
dataloder = DataLoader(dataset, batch_size=2, shuffle=True)

for batch in dataloder:
    print(batch)

# tendor가 두개씩임

[[tensor([3, 1]), tensor([4, 2])], tensor([1, 0])]
[[tensor([5]), tensor([6])], tensor([0])]
